name: Terraform-Docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    strategy:
      matrix:
        module:
          - auto-trader
          - infra-ecs-cluster
          - infra-fleet-service
          - infra-networking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docs
        working-directory: ${{ matrix.module }}
        run: |
          if [ -f .terraform-docs.yml ]; then
            npx terraform-docs -c .terraform-docs.yml --output-check .
          fi
