name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tflint:
    strategy:
      matrix:
        module:
          - auto-trader
          - infra-data
          - infra-ecs-cluster
          - infra-fleet-service
          - infra-networking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v3

      - name: Init TFLint
        working-directory: ${{ matrix.module }}
        run: tflint --init

      - name: Run TFLint
        working-directory: ${{ matrix.module }}
        run: tflint
